### ISSUE TITLE
semantic prompter

### ISSUE THREAD

**Issue by zyhbili** [akira-l/SEEG#1]
Nice work. I failed to find any code related to the semantic prompter, and the default bash seems to train a Tri model? Is there any wrong with the released version. Could you give more instruction?

**Comment by akira-l** [comment]
Thanks for your interest. 
In this repository, you can find that only using beat information can achieve comparable performance to Tri-modal SOTA. 
The semantic prompt does not influence the FID too much. I will release the prompt training details after finishing the current work. 
You can also try to train the semantic prompt yourselves. It is a simple classification network related to some semantic labels. I am still interested in how to find more efficient semantic prompt labels and look forward to more discussions with you.

**Comment by zyhbili** [comment]
Thanks for your reply. Would you release the dataset training the semantic prompter ? Or how to prepare the labels? Looking forward to your next update.

**Comment by akira-l** [comment]
Yes. 
The dataset is a tiny subset of the training set. I located some words in the audio (as the reference in SEEG paper) and captured the gesture sections for prompt training.

**Comment by akira-l** [comment]
I have upload the gallery data in this repo. 
Sorry for the delay. I got COVID twice, from September to October, and gradually recovered recently. 
For more information, feel free to contact me.
